### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by water-man** [PaulLereverend/NextcloudDuplicateFinder#2]
Hi Paul,
Nice app you have. Unfortunately the amount of documentation is pretty limited.
I do not know whether it is my HW (RPI4B, 8GB), my OS (Ubuntu 20.04 LTS) or my installation
(Nextcloud 19 snap), but the only thing I get when attempting the CLI is:

_admin@nextcloud:~$ duplicates:find-all -u admin
duplicates:find-all: command not found__

No doubt I'ĺl find something when I start really digging, but it would be so easy for the user when the documentation either gave him the solution or at least a link to the place where he can find it himself.
Something for a next release??
Cheers

**Comment by PaulLereverend** [comment]
Hi 
Thank you for your kind words.
I agree. The documentation can be improved. I will add some details about the command usage.

This command is a nextcloud command that must be used after occ :  `occ duplicates:find-all`.
OCC documentation : https://docs.nextcloud.com/server/15/admin_manual/configuration_server/occ_command.html

Cheers

**Comment by water-man** [comment]
Hi Paul,
Thanks for the hint! After some additional searching I found that the complete command in my case should be:
 _sudo nextcloud.occ duplicates:find-all_         

(how difficult can it be..........?)

the documentation in the link you send me does not pertain to a snap installation.
In my installation there is no /var/www folder and there is no HTTP user www-data. Everything is contained within the snap, including your app. Installing the app only works via the app store. It then ends up in:

_admin@nextcloud:/var/snap/nextcloud/current/nextcloud/extra-apps/
total 40
drwxr-x--- 10 root root 4096 Jul  9 16:58 .
drwxr-xr-x  4 root root 4096 Jul  2 10:51 ..
drwxr-xr-x  8 root root 4096 Jul  2 11:40 bruteforcesettings
drwxr-xr-x  8 root root 4096 Jul  9 16:04 duplicatefinder
drwxr-xr-x  7 root root 4096 Jul  9 15:54 files_3d
drwxr-xr-x 12 root root 4096 Jul  7 10:09 maps
drwxr-xr-x  6 root root 4096 Jul  9 16:58 printer
drwxr-xr-x 10 root root 4096 Jul  3 12:39 spreed
drwxr-xr-x 11 root root 4096 Jul  2 21:31 twofactor_gateway
drwxr-xr-x 10 root root 4096 Jul  2 21:30 twofactor_totp_

For old-timers like me a snap installation  offers a lot of advantages. The installation is as simple as issuing one single command: "snap install nextcloud" and you are up and running.
The disadvantage is that the folder tree is completely different from a manual install, so all of the documentation is worthless.
When you update your app documentation, let me know. I can write the snap version for it.
Regards,
Herman

**Comment by PaulLereverend** [comment]
Done : 8d1bafb

**Comment by water-man** [comment]
Hi Paul, Nathan,
Thanks, simple and effective.

I'm a newby on github but it looks as if I could have done this myself.....
Must get some more insight on how to use this
