### ISSUE TITLE
SQL error: Specified key was too long

### ISSUE THREAD

**Issue by PiQuer** [PaulLereverend/NextcloudDuplicateFinder#32]
When trying to update to version 0.0.9 on nextcloud 21.0.3 I get the following issue:

`An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes
`

**Comment by mikoladz** [comment]
I thinks it is a duplicate of the https://github.com/PaulLereverend/NextcloudDuplicateFinder/issues/34

**Comment by PaulLereverend** [comment]
The latest version (0.0.11) should fix this issue.
