### ISSUE TITLE
DuplicateFinder Update Causes update issues.

### ISSUE THREAD

**Issue by JasonNaughton** [PaulLereverend/NextcloudDuplicateFinder#34]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Running own cloud version 21.0.3.1
2. Update for the duplicator from 0.08 to 0.09 came out
3. Attempted to update and the Update crashed

### Expected behaviour
I was using my nextcloud instance for the past few weeks without any issues.  The duplicator update came out 0.0.9 and I attempted the update via the web interface.   Sadly the response was:

Update to 21.0.3.1
Exception: Database error when running migration latest for app duplicatefinder

Detailed logs 
Preparing update
Set log level to debug
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Updated database
Exception: Database error when running migration latest for app duplicatefinder

The update was unsuccessful. Please report this issue to the Nextcloud community.

### Actual behaviour
nextcloud is no longer operational.

### Server configuration

**Operating system:**
Linux Mint 20.2

**Web server:**
Apache 2.4.41

**Database:**

mysql 8.0.25

**PHP version:**

php 7.4

**Nextcloud version:** (see Nextcloud admin page)

(can't access the admin page right now or any other page as the site is down but I believe the version is 20.0.3)

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated the app from existing version.

**Where did you install Nextcloud from:**

Downloaded it from the nextcloud site.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

Sadly All I get when I go to this URL is:

App update required
The following apps will be updated:
Duplicate Finder (duplicatefinder)
Please make sure that the database, the config folder and the data folder have been backed up before proceeding.


</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.naughton.ca"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.3.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "CA",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No


</details>

### Client configuration
Chrome

**Operating system:**
Linux Mint 20.2
### Logs

<!--- Reports without logs might be closed as unqualified reports! -->

#### Web server error log
<details>
<summary>Web server error log</summary>
None
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Quite large..

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by JasonNaughton** [comment]
managed to simply restore nextcloud folder proir to update, restored database, logged into site, disabled APP, and then removed app.  Coudn't have this disable my entire site.

**Comment by z0ow** [comment]
after disable then enable app through occ commands, got an exception message as follows:
```
php occ app:enable duplicatefinder                                                                                                                        
An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes
```
OS: Centos: 7.9
Database: MySQL 8.0.25
NC: 22.0.0

**Comment by PaulLereverend** [comment]
@chrros95 do you have an idea on this ?

**Comment by chrros95** [comment]
Ok, so it looks like mariadb and mysql handle the index limit differently - while mariadb simply cuts the index size; mysql throws an error.
Tomorrow, I'll develop a workaround to handle this and try to implement a testing for mysql as well

**Comment by terencedesu** [comment]
I am experiencing the same problem. I can't get into my Nextcloud as long as this is not working. I checked config.php and it is not in maintenance mode, so I am not sure what to do. Is there any way I can temporarily disable the app so it doesn't want to update and I can get into my nextcloud?

**Comment by WNYmathGuy** [comment]
I had this happen to me too this morning:
[Exception: Database error when running migration latest for app duplicatefinder #27972](https://github.com/nextcloud/server/issues/27972)

**Comment by z0ow** [comment]
> I am experiencing the same problem. I can't get into my Nextcloud as long as this is not working. I checked config.php and it is not in maintenance mode, so I am not sure what to do. Is there any way I can temporarily disable the app so it doesn't want to update and I can get into my nextcloud?

A better way to handle this problem is using the `php ./occ app:disable duplicatefinder` command to temporarily disable DuplicateFinder and avoid automatically redirected to the update page.

**Comment by terencedesu** [comment]
> A better way to handle this problem is using the `php ./occ app:disable duplicatefinder` command to temporarily disable DuplicateFinder and avoid automatically redirected to the update page.

zDow - thanks for this. It worked. I was thinking it might but didn't want to risk it since it the update had already been installed and it was no longer in maintenance mode.

**Comment by Spam-Spamych** [comment]
In SNAP the command "php ./occ app:disable duplicatefinder" not working.
How i can disable the app in SNAP?

**Comment by JasonNaughton** [comment]
Sadly I did exactly the:
php occ app:disable duplicatefinder

Yet when I went back to my nextcloud interface, I could login but the entire site CSS was buggered which I didn't know how that could be. This is why I went back to my backups of the night prior, restored the database and nextcloud which only had the 0.0.8 release. I could then disable, and remove the app.

**Comment by chrros95** [comment]
Sorry, for the inconveniences you have encountered. 
PR #36 should provided a fix for the issue.

**Comment by JasonNaughton** [comment]
No problem @chrros95.   To be honest I didn’t think that the file duplicator would have such a large impact on the site.  I saw it as a single plugin which when removed would end it’s effect.   When I issued the occ to disable the app, and went back to the web interface it was if all the CSS rendering had messed up.  The site was referred back to a strictly html markup site.  I could login but it was pointless.     That’s why I backed out and restored.

**Comment by NicolasGoeddel** [comment]
I've got the same error today. I was able to solve the issue by disabling the app with `occ`.
How can I update to the latest version without enabling it again? Because as soon as I enable the app I run into the same problem again and the whole webinterface gets blocked.

**Comment by chrros95** [comment]
Please try, to remove the app with `occ app:remove duplicatefinder`. Afterwards, the update should work as expected.
If you like to use the app until the fix has been released, please download the [release archive](https://github.com/PaulLereverend/NextcloudDuplicateFinder/releases/tag/0.0.8) and extract it to your apps folder.

**Comment by PaulLereverend** [comment]
The fix has been build. Can somebody please try it and confirm it does fix the issue before I upload to nextcloud appstore ? 
The archive is available here : https://github.com/PaulLereverend/NextcloudDuplicateFinder/releases/tag/0.0.10

**Comment by z0ow** [comment]
@PaulLereverend 

Version 0.0.10 is no problem installing and enabling in NC now. A new issue is raised that when using duplicatefinder through the web interface, the loading page is just showing instantly, then print no duplicate files found. It is abnormal because I am certain there are many duplicate files in my server, so must something goes wrong in the find step. 

After many times ran duplicatefinder fails, I am trying to perform `php occ duplicates:find-all`, but it throws an exception as follows:

```
> $ php occ duplicates:find-all                                                                                                                               
Start searching files for admin in path /admin/files

In DbalException.php line 71:
                                                                                                                                  
  An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1364 Field 'owner' doesn't have a default value  
                                                                                                                                  

In ExceptionConverter.php line 111:
                                                                                                                                  
  An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1364 Field 'owner' doesn't have a default value  
                                                                                                                                  

In Exception.php line 26:
                                                                                   
  SQLSTATE[HY000]: General error: 1364 Field 'owner' doesn't have a default value  
                                                                                   

In Statement.php line 82:
                                                                                   
  SQLSTATE[HY000]: General error: 1364 Field 'owner' doesn't have a default value  
                                                                                   

duplicates:find-all [-u|--user USER] [-p|--path PATH] [--output [OUTPUT]]

                                                                         
```

**Comment by chrros95** [comment]
@z0ow Thanks for the test.
With an error like this, I would expect messages like "There is a problem with the owner of <path>" in the Nextcloud log.
Before or afterwards there should be a backtrace for duplicatefinder. 
Can you please confirm, if such messages exist and show us one of them?

**Comment by z0ow** [comment]
@chrros95  No worries. Those Nextcloud logs are related to "There is a problem with the owner of ...":

```                                                                                   
{"reqId":"O8dtJZFxKPQD42U9VG8D","level":4,"time":"2021-07-16T23:20:43+00:00","remoteAddr":"","user":"--","app":"duplicatefinder","method":"","url":"--","message":"There is a problem with the owner of /admin/files/\u7535\u5f71/X-Men First Class 3D SBS 1080p.mkv","userAgent":"--","version":"22.0.0.11"}
{"reqId":"aVoz6uPKOKgDhRc9NDfH","level":4,"time":"2021-07-17T02:56:56+00:00","remoteAddr":"","user":"--","app":"duplicatefinder","method":"","url":"--","message":"There is a problem with the owner of /admin/files/\u7535\u5f71/X-Men First Class 3D SBS 1080p.mkv","userAgent":"--","version":"22.0.0.11"}
```

The `/admin/files/\u7535\u5f71/X-Men First Class 3D SBS 1080p.mkv` is located in the folder '/电影/'(\u7535\u5f71). This folder is mounted by external storage app and the permission for users is r+w.

**Comment by PaulLereverend** [comment]
@z0ow the latest version should fix your issue. 
Can you confirm you are able to get the list of your duplicate files ? 

Version 0.0.11 available here : https://github.com/PaulLereverend/NextcloudDuplicateFinder/releases/tag/0.0.11

**Comment by z0ow** [comment]
@PaulLereverend Version 0.0.11 is working fine for me. Thanks for your help 👍

**Comment by PaulLereverend** [comment]
Thank you for your time. This version has been pushed to the app store.
