### ISSUE TITLE
It is unclear what clear does

### ISSUE THREAD

**Issue by Drugoy** [PaulLereverend/NextcloudDuplicateFinder#44]
Hello.
`clear       The command will clear all information that has been stored in the database options`
Does it mean it will just remove links to duplicate files from the database and will leave all those files dangling on the disk?

If so, I've got an obvious FR: provide a way to also remove those files from the disk.
If not - please, improve the command's description: it should leave no room for doubt.

**Comment by chrros95** [comment]
The command doesn't touch or unlink files. It only removes information from the database.
An FR for automated deleting has already been opened by #16.

Regarding the suggestion to improve the description, do you have any wording in mind which is more clear?
If so, you are welcome to create a PR - you only need to change this line:
https://github.com/PaulLereverend/NextcloudDuplicateFinder/blob/6068efd9d54539c0daec4b02c54685706f45000b/lib/Command/ClearDuplicates.php#L55

If don't like to create a PR, you may drop it here so I can consider adding it a PR

**Comment by Drugoy** [comment]
Thank you for the answer @chrros95 !
Now that I know what it does I'd suggest the following wording:
`clear - Remove links to interactively recognized duplicate files from the database of your Nextcloud instance. This action doesn't remove the files from your file system.`

**Comment by chrros95** [comment]
I've added this description as help text to the command and committed it to PR #41.
So it will be visible if the user executes `./occ duplicates:clear --help`

https://github.com/PaulLereverend/NextcloudDuplicateFinder/blob/aa90b9f2ea660be48785c735f20f1e6fa4bffbf5/lib/Command/ClearDuplicates.php#L56-L59

![image](https://user-images.githubusercontent.com/9655096/129366438-6ab076bb-7440-456d-b369-5c4bd2dc57f5.png)

Hope that suits you.

**Comment by MarkoPaasila** [comment]
It's still not clear to me. Could you please clarify:
1. Does `duplicates:clear`
  a. remove references to all copies except one, or
  b. clear the list of detected duplicates
3. Does _remove links_ mean the files are effectively invisible to the user, or can the files still be found in "trash"?
4. Which is the one **not** removed?
5. What does "interactively recognized" mean? Isn't detection automatic. Or does this mean that the trash button doesn't do what I think it does: to delete the selected file (move it into trash) - and duplicates:clear actually moves them into trash?

Sorry for so many - probably stupid - questions. I already ran the `duplicates:clear` command, and now am trying to understant what it actually did.
