### ISSUE TITLE
All files have Identical hashes after update.

### ISSUE THREAD

**Issue by mpyusko** [PaulLereverend/NextcloudDuplicateFinder#52]
I just update to the 0.0.12 and every file in the system was suddenly a duplicate, displaying the same hashes.

**Comment by PaulLereverend** [comment]
From which version did you update ?
You can try fixing the issue by running `php occ maintenance:repair`

**Comment by jmbmkn** [comment]
I also have this issue, I'm not sure what version I updated from, but I usually update installed apps every few weeks. Succesfully ran `occ maintainance:repair` but it did not resolve the issue.

**Comment by mpyusko** [comment]
I wound up running duplicates:clear and then duplicates:find-all to resolve the issue.  But that's a pretty intense resolution.Sent from my Verizon, Samsung Galaxy smartphone

**Comment by chrros95** [comment]
Indeed `./occ duplicates:clear` and then `./occ duplicates:find-all` should fix errors like this.
@jmbmkn If you still have the issue, can you please verify if the issue persists on the CLI?

Can both of you please elaborate, which Nextcloud version and database at which version are you using?

**Comment by chrros95** [comment]
And another question, are your logs show any exceptions regarding the app?

**Comment by vwbusguy** [comment]
On Nextcloud 22.1.1, upgrading to 0.12 actually crashed nextcloud and after taking it out of maintenance mode, it initiated a repair, which triggered the deplicates app to recalculate hashes on every file, which as you can imagine wasn't a small amount of downtime.

**Comment by vwbusguy** [comment]
So after all of that and an hour and a half later, now my files all have the same hash, so the same problem as OP.  I'll try the clear and find-all later tonight.

**Comment by chrros95** [comment]
I'm still not able to reproduce the issue.
So can users who are affected please try to specify more information like
- which PHP version is used?
- does the issue always occurred while upgrading Nextcloud?
- is the issue also present, when listing the duplicates on cli via `./occ duplicates:list -u <your user id>`
- is there any error present in the log files?
- is any PHP caching used?

**Comment by vwbusguy** [comment]
- php-7.4.23-1.fc34.x86_64
- No.  It didn't happen on upgrading Nextcloud for me.  It happened on updating this app.  Haven't seen it before the recent update.
- On CLI - It actually shows some different hashes but still generally a large amount of very much not duplicates associated with each (pictures, songs, database backups all under the same hash).
- I don't see anything obviously related in apache or php logs during that time
- Using redis for caching

**Comment by vwbusguy** [comment]
So on the day I did the migration, I do see these two identical errors:

```
[10-Sep-2021 10:28:08 UTC] PHP Fatal error:  Uncaught Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory in /srv/nextcloud/lib/private/DB/Connection.php:87
Stack trace:
#0 /srv/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1486): OC\DB\Connection->connect()
#1 /srv/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1014): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /srv/nextcloud/lib/private/DB/Connection.php(231): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM `...', Array, Array, NULL)
#3 /srv/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(210): OC\DB\Connection->executeQuery('SELECT * FROM `...', Array, Array)
#4 /srv/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(287): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /srv/nextcloud/lib/private/AppConfig.php(344): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /srv/nextcloud/lib/private/AppConfig.php(109): OC\AppConfig->loadConfigValues()
#7 /srv/nextcloud/lib/private in /srv/nextcloud/lib/private/DB/Connection.php on line 87
```

The diff between the versions suggests this *might* be it but unfortunately the logs don't traceback and further: https://github.com/PaulLereverend/NextcloudDuplicateFinder/compare/0.0.11...0.0.12#diff-06425a8283fed2ad484bbb28026406f88e762b39b8fc866e8eab741ab5f74840R99

I don't have anything corresponding in the database logs.
