### ISSUE TITLE
Nextcloud becomes unresponsive after trying to use duplicate finder

### ISSUE THREAD

**Issue by jmigual** [PaulLereverend/NextcloudDuplicateFinder#54]
When I open the duplicate finder app Nextcloud does not answer any more queries and the CPU usage reaches 100% as it's using all the cores together with php and MySQL.

Eventually it produces a 504 Gateway Time-out however after a while (~20 minutes) it becomes responsive again as long as I don't go to the Duplicate Finder app.

Duplicate Finder Version Version: 0.0.12
Nextcloud Version: 21.0.4
PHP version: 7.4.23
MariaDB version: 10.6.4-MariaDB-1:10.6.4+maria~focal-log

**Comment by chrros95** [comment]
Thanks for the report.
I guess I have made a stupid mistake. Can you please try to add `$offset = $lastKey;` right below https://github.com/PaulLereverend/NextcloudDuplicateFinder/blob/e861a6d72b6d54cd0e86a392af0022ca0397d7b1/lib/Service/FileDuplicateService.php#L90

**Comment by jmigual** [comment]
Hi, after adding the line nextcloud is able to continue working properly after opening duplicate finder. So the issue is solved.

If you don't mind I'll leave the issue open until you release a fix.

**Comment by jmigual** [comment]
The only issue I see now is that it doesn't load anything and just shows the loading gif endlessly. By checking with htop I see some CPU usage of mariaDB but then CPU usage goes to near 0 and it doesn't load anything.

**Comment by chrros95** [comment]
Hm, I'm not sure what is happening.

Can you please open the developer tools, reload the page and check if the console shows any error?
If you don't mind, it would be nice if you can verify if the console output has an error es well by using `./occ duplicates:list` and `./occ duplicates:list -u <your user id>`

**Comment by jmigual** [comment]
The output of the console is the following:

```
No OC found index.js:46:12
JQMIGRATE: Migrate is installed, version 3.3.2 jquery-migrate.min.js:2:708
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
Notifications permissions granted App.vue:306
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 2 globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
session heartbeat polling started session-heartbeat.js:97:9
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, app: "unified-search", uid: "<redacted>" }
```

I did run `occ duplicates:list` and it didn't seem to have an error but I didn't let it finish as I have a lot of duplicates and after 10 minutes it was still going. Maybe I'll let it run during the night and save the output.

**Comment by jmigual** [comment]
Alright, after successfully running `occ duplicates:list` there were no errors and the command ran successfully without problems.

**Comment by goher-naushahi** [comment]
hey guys, I changed the line 90 as suggested and start getting results however I wonder how can different files have same hash..  i.e. pdf files.. photos. etc.
something seems wrong. 

![image](https://user-images.githubusercontent.com/58830144/132949519-b2194776-b329-430e-aedf-179e8450f6a6.png)

**Comment by jmigual** [comment]
@goher-naushahi please see #52

**Comment by chrros95** [comment]
Sorry for the delayed response. I wasn't able to reproduce your issue @jmigual but due to the fact the CLI works fine, it might be related to the javascript. To resolve this I've tried to improved error handling. Can you please try to exchange the js/script.js with https://github.com/chrros95/NextcloudDuplicateFinder/blob/issue_54/js/script.js, clear the cache browser cache and check the developer tools again?

**Comment by jmigual** [comment]
Hi, apologies for the delay. I'll try your suggestion and come back to you in about a week.
