### ISSUE TITLE
Issue with Nextcloud 24.0.0

### ISSUE THREAD

**Issue by JWebCoder** [PaulLereverend/NextcloudDuplicateFinder#72]
Nextcloud Version: 24.0.0
duplicate finder version: 0.0.14

Running: occ duplicates:find-all

I'm getting some console errors.

Start searching files for ***** in path /*****/files
An unhandled exception has been thrown:
TypeError: Argument 4 passed to OC\Files\Utils\Scanner::__construct() must implement interface Psr\Log\LoggerInterface, instance of OC\AppFramework\Logger given, called in /var/www/nextcloud/apps/duplicatefinder/lib/Utils/ScannerUtil.php on line 78 and defined in /var/www/nextcloud/lib/private/Files/Utils/Scanner.php:95
Stack trace:
0 /var/www/nextcloud/apps/duplicatefinder/lib/Utils/ScannerUtil.php(78): OC\Files\Utils\Scanner->__construct()
1 /var/www/nextcloud/apps/duplicatefinder/lib/Utils/ScannerUtil.php(68): OCA\DuplicateFinder\Utils\ScannerUtil->initializeScanner()
2 /var/www/nextcloud/apps/duplicatefinder/lib/Service/FileInfoService.php(256): OCA\DuplicateFinder\Utils\ScannerUtil->scan()
3 /var/www/nextcloud/apps/duplicatefinder/lib/Command/FindDuplicates.php(152): OCA\DuplicateFinder\Service\FileInfoService->scanFiles()
4 /var/www/nextcloud/apps/duplicatefinder/lib/Command/FindDuplicates.php(112): OCA\DuplicateFinder\Command\FindDuplicates->findDuplicates()
5 /var/www/nextcloud/lib/private/User/Manager.php(551): OCA\DuplicateFinder\Command\FindDuplicates->OCA\DuplicateFinder\Command\{closure}()
6 /var/www/nextcloud/apps/duplicatefinder/lib/Command/FindDuplicates.php(113): OC\User\Manager->callForAllUsers()
7 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\DuplicateFinder\Command\FindDuplicates->execute()
8 /var/www/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
12 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
13 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
14 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
15 {main}

Thank you.

**Comment by webartifex** [comment]
Hi, I am getting the same error message on 24.0.1 as well. I am new to NC but if you tell me how I could contribute to fixing it.

**Comment by ilsawa** [comment]
I have the same error after upgrading to 24.0.1 on two servers

**Comment by maxtoor** [comment]
Same error. NC 24.0.1 Php 8.0

**Comment by andyxheli** [comment]
Same issue NC 24.0.2 PHP 8.1 applied the https://github.com/bonswouar/NextcloudDuplicateFinder/commit/aefbade42156f6a920265cc8dfe0e449205d76f3 and fixed the issue.
